### ISSUE TITLE
how to modify the batch size during inference?

### ISSUE THREAD

**Issue by wmkai** [hustvl/TopFormer#15]
I tried to modify the value `samples_per_gpu` from 2 to 1 in config file, but the `elapsed` time in inference log seems to change not much. Do I have something wrong?

**Comment by speedinghzl** [comment]
The change of elapsed time does not indicate the batch size per GPU precisely. It could be better to print the batch size when testing.

**Comment by wxz1996** [comment]
@speedinghzl sor, i tried to modify **samples_per_gpu** and  **gpu_id** for training， but it don't work

**Comment by wmkai** [comment]
I see, thanks a lot.
