### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ke-dev** [hustvl/TopFormer#16]
Hello, developer, when I try to run in mmsegmentation environment, I get the following error
`FileNotFoundError: modelzoos/classification/topformer-T-224-66.2.pth can not be found.`
where should I get this file?
`topformer-T-224-66.2.pth`

**Comment by ke-dev** [comment]
The command I run is `bash tools/dist_train.sh local_configs/topformer/topformer_tiny_512x512_160k_2x8_ade20k.py`

**Comment by ke-dev** [comment]
bash tools/dist_train.sh local_configs/topformer/topformer_tiny_512x512_160k_2x8_ade20k.py 1

**Comment by ke-dev** [comment]
The command I run is `bash tools/dist_train.sh local_configs/topformer/topformer_tiny_512x512_160k_2x8_ade20k.py 1`

**Comment by ke-dev** [comment]
The problem is solved，set `checkpoint=None`

**Comment by speedinghzl** [comment]
You can find the download links of classification models from [ReadMe](https://github.com/hustvl/TopFormer#main-results).

**Comment by youcandoanythingya** [comment]
Hello, I have the same problem, how can I solve it？
