### ISSUE TITLE
is there any ImageNet pre-training config of Topformer?

### ISSUE THREAD

**Issue by wmkai** [hustvl/TopFormer#17]
I want to change some modules when using Topformer to do classification on ImageNet. Could you please provide the ImageNet Pre-training config? Thanks!

**Comment by speedinghzl** [comment]
Please look into [the close issue](https://github.com/hustvl/TopFormer/issues/5). You could obtain the classification model by removing SIM in the Seg model and adding a Linear layer on the top of the Transformer block (SASE) as the classification head.

**Comment by wmkai** [comment]
If it is convenient for you, can I have your wechat and share the code of imagenet pre-training?
