### ISSUE TITLE
对比实验

### ISSUE THREAD

**Issue by vozhuo** [hustvl/TopFormer#23]
请问论文Table 1里面的对比方法全都是用MMSegmentation做的吗，我想跑一下对比方法但是我发现好多模型没有找到，比如DeepLabV3+ EfficientNet、DeepLabV3+ ShuffleNetV2-1.5x、Semantic FPN ConvMLP-S等，configs里面没有相关的代码。

**Comment by mulinmeng** [comment]
是在MMSeg下跑的，在mmseg下实现的EfficientNet，相同的setting下进行对比。MMseg已经有实现DeepLabV3+,只需要添加backbone即可。
Semantic FPN ConvMLP-S是引用的结果，可以到对应的paper中找到，他们也是基于mmseg实现的。
