### ISSUE TITLE
Classification cfg?

### ISSUE THREAD

**Issue by xperzy** [hustvl/TopFormer#5]
Hello, could you please provide the cfgs (e.g., classification head) for classification model? 

Thanks.

**Comment by mulinmeng** [comment]
> Hello, could you please provide the cfgs (e.g., classification head) for classification model?
> 
> Thanks.

Thanks for your ask! You can view specific settings from the [classification checkpoint](https://pan.baidu.com/s/1YdrU-5Z_EtL2LiSQycRO3w). 

The classification head is a Linear-BN layer. The detailed structure is shown in Figure 5 of the [arxiv paper](https://arxiv.org/abs/2204.05525).
