### ISSUE TITLE
size of output

### ISSUE THREAD

**Issue by javadmozaffari** [hustvl/TopFormer#8]
Hello, 
As shown in figure 2, 1/4 scale of input is present in the output. so for 448*448 input, there is a 56*56 image in the output!!! what is the point that I can't see?

**Comment by mulinmeng** [comment]
> Hello, As shown in figure 2, 1/4 scale of input is present in the output. so for 448_448 input, there is a 56_56 image in the output!!! what is the point that I can't see?

Thanks for your ask!  We have provided the detailed implementation in Sec.3.4 and conducted related experiments in Tab. 3. You can decide whether to add 1/4 features according to your hardware  device.
